### ISSUE TITLE
Data Tailor Cleanup didn't work

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#162]
**Describe the bug**
The Download Manager's cleanup() method failed when trying to clear the data tailor storage quickly , and giving a 500 internal server error. Admittedly, I was also trying to clear it for awhile from the web portal, so that could be it, but good to check as if it fills up totally, it will crash forecasts when the RSS stops.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jacobbieker** [comment]
Ran it again after clearing out the data tailor, and waiting awhile. It still fails, even with completed customizations available to delete.

Gives:

```
Traceback (most recent call last):
  File "/home/jacob/anaconda3/envs/xbit2/lib/python3.10/site-packages/eumdac/errors.py", line 16, in eumdac_raise_for_status
    response.raise_for_status()
  File "/home/jacob/anaconda3/envs/xbit2/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations/delete

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacob/Development/Satip/scripts/modal_processing.py", line 229, in <module>
    download_manager.cleanup_datatailor()
  File "/home/jacob/Development/Satip/satip/eumetsat.py", line 518, in cleanup_datatailor
    customisation.delete()
  File "/home/jacob/anaconda3/envs/xbit2/lib/python3.10/site-packages/eumdac/customisation.py", line 193, in delete
    eumdac_raise_for_status("Failed to patch tailor delete", response, CustomisationError)
  File "/home/jacob/anaconda3/envs/xbit2/lib/python3.10/site-packages/eumdac/errors.py", line 25, in eumdac_raise_for_status
    raise exception from exc
eumdac.customisation.CustomisationError: Failed to patch tailor delete
```

**Comment by jacobbieker** [comment]
I believe this is now fixed, as when running it works now.
