### ISSUE TITLE
Permission Denied on creating file

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#26]
**Describe the bug**

**To Reproduce**
1. Run download script on leonardo for dates other than 2020/2021
```
PermissionError: [Errno 13] Permission denied: '/mnt/storage_a/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/native/2018/11/13/MSG3-SEVI-MSG15-0100-NA-20181113041418.116000000Z-NA.nat.bz2'
Error [Errno 13] Permission denied: '/mnt/storage_a/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/native/2018/11/13/MSG3-SEVI-MSG15-0100-NA-20181113041918.181000000Z-NA.nat.bz2' when sanity-checking /mnt/storage_a/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/native/MSG3-SEVI-MSG15-0100-NA-20181113041918.181000000Z-NA.nat.  Deleting this file.  Will be downloaded next time this script is run.
Traceback (most recent call last):
  File "/home/jacob/Satip/satip/download.py", line 257, in process_rss_images
    fs.move(
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/fsspec/spec.py", line 1171, in move
    return self.mv(path1, path2, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/fsspec/spec.py", line 883, in mv
    self.copy(path1, path2, recursive=recursive, maxdepth=maxdepth)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/fsspec/spec.py", line 845, in copy
    self.cp_file(p1, p2, **kwargs)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/site-packages/fsspec/implementations/local.py", line 114, in cp_file
    shutil.copyfile(path1, path2)
  File "/home/jacob/miniconda3/envs/ocf/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/mnt/storage_a/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/native/2018/11/13/MSG3-SEVI-MSG15-0100-NA-20181113041918.181000000Z-NA.nat.bz2'
```

**Expected behavior**

**Additional context**

**Comment by jacobbieker** [comment]
Group permissions gave rad but not write! Fixed it now for those two folders
