### ISSUE TITLE
Bug with time range on backfill pipeline

### ISSUE THREAD

**Issue by Rabscuttler** [openclimatefix/Satip#6]
```
NING - 2021-03-20 15:28:12,702 - INFO - ********** Download Manager Initialised **************
[2021-03-20 15:28:12,703] {logging_mixin.py:112} INFO - [2021-03-20 15:28:12,702] {eumetsat.py:327} INFO - ********** Download Manager Initialised **************
[2021-03-20 15:28:12,791] {logging_mixin.py:112} INFO - Earliest 2020-01-09T00:00:00, latest 2020-01-13T00:00:00
[2021-03-20 15:28:12,798] {logging_mixin.py:112} WARNING - 2021-03-20 15:28:12 - dagster - ERROR - download_missing_data_pipeline - manual__2021-03-20T15:27:52.932900+00:00 - 17566 - download_missing_eumetsat_files.compute - STEP_FAILURE - Execution of step "download_missing_eumetsat_files.compute" failed.

ipypb.progressbar.ProgressBarInputError: Please specify the total number of iterations

  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/errors.py", line 180, in user_code_error_boundary
    yield
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/execute_step.py", line 475, in _user_event_sequence_for_step_compute_fn
    for event in iterate_with_context(raise_interrupts_immediately, gen):
  File "/srv/airflow/lib/python3.7/site-packages/dagster/utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 105, in _execute_core_compute
    for step_output in _yield_compute_results(compute_context, inputs, compute_fn):
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 76, in _yield_compute_results
    for event in user_event_sequence:
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py", line 230, in compute
    for item in result:
  File "/srv/airflow/lib/python3.7/site-packages/satip/backfill.py", line 54, in download_missing_eumetsat_files
    missing_datasets = io.identifying_missing_datasets(start_date, end_date)
  File "/srv/airflow/lib/python3.7/site-packages/satip/io.py", line 189, in identifying_missing_datasets
    for i in track(range(len(month_split)-1)):
  File "/srv/airflow/lib/python3.7/site-packages/ipypb/progressbar.py", line 118, in __init__
    raise ProgressBarInputError('Please specify the total number of iterations')
[2021-03-20 15:28:12,879] {taskinstance.py:1145} ERROR - step failed with error: (ProgressBarInputError) - ipypb.progressbar.ProgressBarInputError: Please specify the total number of iterations

Stack Trace: 
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/errors.py", line 180, in user_code_error_boundary
    yield
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/execute_step.py", line 475, in _user_event_sequence_for_step_compute_fn
    for event in iterate_with_context(raise_interrupts_immediately, gen):
  File "/srv/airflow/lib/python3.7/site-packages/dagster/utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 105, in _execute_core_compute
    for step_output in _yield_compute_results(compute_context, inputs, compute_fn):
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 76, in _yield_compute_results
    for event in user_event_sequence:
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py", line 230, in compute
    for item in result:
  File "/srv/airflow/lib/python3.7/site-packages/satip/backfill.py", line 54, in download_missing_eumetsat_files
    missing_datasets = io.identifying_missing_datasets(start_date, end_date)
  File "/srv/airflow/lib/python3.7/site-packages/satip/io.py", line 189, in identifying_missing_datasets
    for i in track(range(len(month_split)-1)):
  File "/srv/airflow/lib/python3.7/site-packages/ipypb/progressbar.py", line 118, in __init__
    raise ProgressBarInputError('Please specify the total number of iterations')
Traceback (most recent call last):
  File "/srv/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/srv/airflow/lib/python3.7/site-packages/dagster_airflow/vendor/python_operator.py", line 108, in execute
    return_value = self.execute_callable()
  File "/srv/airflow/lib/python3.7/site-packages/dagster_airflow/vendor/python_operator.py", line 113, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/airflow/lib/python3.7/site-packages/dagster_airflow/operators/python_operator.py", line 10, in python_callable
    dagster_operator_parameters.invocation_args, ts, dag_run, **kwargs
  File "/srv/airflow/lib/python3.7/site-packages/dagster_airflow/operators/util.py", line 142, in invoke_steps_within_python_operator
    check_events_for_failures(events)
  File "/srv/airflow/lib/python3.7/site-packages/dagster_airflow/operators/util.py", line 16, in check_events_for_failures
    "step failed with error: %s" % event.event_specific_data.error.to_string()
airflow.exceptions.AirflowException: step failed with error: (ProgressBarInputError) - ipypb.progressbar.ProgressBarInputError: Please specify the total number of iterations

Stack Trace: 
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/errors.py", line 180, in user_code_error_boundary
    yield
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/execute_step.py", line 475, in _user_event_sequence_for_step_compute_fn
    for event in iterate_with_context(raise_interrupts_immediately, gen):
  File "/srv/airflow/lib/python3.7/site-packages/dagster/utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 105, in _execute_core_compute
    for step_output in _yield_compute_results(compute_context, inputs, compute_fn):
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/execution/plan/compute.py", line 76, in _yield_compute_results
    for event in user_event_sequence:
  File "/srv/airflow/lib/python3.7/site-packages/dagster/core/definitions/decorators/solid.py", line 230, in compute
    for item in result:
  File "/srv/airflow/lib/python3.7/site-packages/satip/backfill.py", line 54, in download_missing_eumetsat_files
    missing_datasets = io.identifying_missing_datasets(start_date, end_date)
  File "/srv/airflow/lib/python3.7/site-packages/satip/io.py", line 189, in identifying_missing_datasets
    for i in track(range(len(month_split)-1)):
  File "/srv/airflow/lib/python3.7/site-packages/ipypb/progressbar.py", line 118, in __init__
    raise ProgressBarInputError('Please specify the total number of iterations')

[2021-03-20 15:28:12,880] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=download_missing_data_pipeline, task_id=download_missing_eumetsat_files, execution_date=20210320T152752, start_date=20210320T152812, end_date=20210320T152812
[2021-03-20 15:28:22,000] {logging_mixin.py:112} INFO - [2021-03-20 15:28:22,000] {local_task_job.py:103} INFO - Task exited with return code 1
```

**Comment by jacobbieker** [comment]
This code has now been removed to refocus Satip with #7 with the EUMETSAT data transformation and such now taking place in `nowcasting-dataset`
